# Generated by Django 4.0 on 2022-02-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='item_name',
        ),
    ]
